/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "dmoRTOS.h"
#include "task.h"
#include "semphr.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU baslatilmadi, ancak proje bir FPU için derleniyor. Lutfen kullanmadan önce FPU'yu baslatin."
#endif

uint32_t task0_profiler = 0;

uint32_t task1_profiler = 0;

uint32_t task2_profiler = 0;

uint32_t task3_profiler = 0;

semaphore_t semphr_1;


void task0(void)
{
	while(1)
	{
		task0_profiler++;
		xTaskWait();
	}
}
void task1(void)
{
	while(1)
	{
		task1_profiler++;
		xTaskWait();
	}
}
void task2(void)
{
	while(1)
	{
		task2_profiler++;
		xTaskWait();
	}
}

void task3(void)
{
	while(1)
	{
		task3_profiler++;
		xTaskWait();
	}
}

int main(void)
{
	semphr_1 = xSemaphoreCreate(1);

	xTaskCreate(&task0, 500);
	xTaskCreate(&task1, 50);
	xTaskCreate(&task2, 3000);
	xTaskCreate(&task3, 1);

	xTaskStartScheduler();
}
